# Generated by Django 4.2 on 2023-04-20 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='donde',
            new_name='done',
        ),
    ]
